services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-assessment-cms
    restart: always
    tty: true
    expose:
      - "9000"
    volumes:
      - student-assessment-cms-data:/var/www/app
      - ./storage/app/public:/var/www/app/storage/public
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - student-assessment-cms-network

  caddy:
    image: docker.io/caddy:alpine
    container_name: student-assessment-caddy
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - student-assessment-cms-data:/var/www/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/deploy/student-assessment-exam:/home/deploy/student-assessment-exam
    depends_on:
      - app
    networks:
      - student-assessment-cms-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-assessment-cms-queue
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage/app/public:/var/www/app/storage/public
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      - mysql
      - redis
    networks:
      - student-assessment-cms-network

  mysql:
    image: docker.io/mysql:8.0.45-bookworm
    container_name: student-assessment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student_assessment
      MYSQL_USER: student
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - student-assessment-cms-network

  redis:
    image: docker.io/redis:8.6.0-alpine
    container_name: student-assessment-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - student-assessment-cms-network

volumes:
  student-assessment-cms-data:
  mysql-data:
  redis-data:

networks:
  student-assessment-cms-network:
    driver: bridge
