services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-base
    container_name: digiexam-demo
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./storage/app:/var/www/app/storage/app
      - ./public:/var/www/app/public
      - ./database:/var/www/app/database
    env_file:
      - .env
    networks:
      - digiexam-network

networks:
  digiexam-network:
    driver: bridge