services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: student-assessment-cms
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c "composer install && npm ci && php artisan octane:start --watch"
    depends_on:
      - mysql
      - redis
      -
  vite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: student-assessment-vite
    volumes:
      - ./:/app
    command: npm run dev
    ports:
      - "5173:5173"

  queue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: student-assessment-cms-queue
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.45-bookworm
    container_name: student-assessment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student_assessment
      MYSQL_USER: student
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis:8.6.0-alpine
    container_name: student-assessment-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
