FROM dunglas/frankenphp:php8.4

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl git unzip nodejs npm \
    && rm -rf /var/lib/apt/lists/* \
    && install-php-extensions pdo_mysql intl zip gd opcache pcntl redis

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Tidak copy source code!
# Semua dimount dari volume

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
