[www]
user = www-data
group = www-data
listen = 9000

pm = dynamic
pm.max_children = 60        ; worker maksimal sesuai RAM
pm.start_servers = 20       ; worker awal saat start container
pm.min_spare_servers = 15   ; worker idle minimal
pm.max_spare_servers = 40   ; worker idle maksimal
pm.max_requests = 2000      ; worker recycle setelah request tertentu
request_terminate_timeout = 30s

; Opcache
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.memory_consumption] = 128
php_admin_value[opcache.interned_strings_buffer] = 8
php_admin_value[opcache.max_accelerated_files] = 10000
php_admin_value[opcache.revalidate_freq] = 2
php_admin_value[opcache.validate_timestamps] = 1

; Memory limit per worker
php_admin_value[memory_limit] = 256M
