name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/ndik/DEV/jkims-app   # ⚠️ ganti path project kamu
          git pull origin main
